### PR TITLE
Update sonar version

### PR DESCRIPTION
**Pull request by clementval**
Update sonar version to avoid CI problem with Java 8

### CODE REVIEW

**Review by FrostyMike — APPROVED** [review]
While the Travis script succeeds now, I am not sure this actually worked. The log says that Sonar analysis finished immediately and the results didn't show up online https://sonarcloud.io/organizations/claw-project/projects?sort=analysis_date

**Comment by lxavier** [comment]
why does the PR shoes changes to the omni submodule ? Is it on purpose ?

**Review by lxavier — APPROVED** [review]

**Comment by clementval** [comment]
> why does the PR shoes changes to the omni submodule ? Is it on purpose ?

There should be no change to the submodule. I'll update that.

**Comment by clementval** [comment]
> While the Travis script succeeds now, I am not sure this actually worked. The log says that Sonar analysis finished immediately and the results didn't show up online https://sonarcloud.io/organizations/claw-project/projects?sort=analysis_date

Right. Probably some change needed in the sonar properties for the newer version. I'll have a look and update appropriately.

**Comment by FrostyMike** [comment]
Sonar was updated in another pull request.

**Pull request closed without merging**
