### PR TITLE
Fusion+scalar in SCA

### PR DESCRIPTION
**Pull request by MDosky**
## Status

**REVIEW**

## Description
Use of loop fusion and keeping of scalars if possible.
It works differently from the other version since it keep track of the variable use in "blocks". It than proceed to use the various sets to know how to handle promotions.

### CODE REVIEW

**Comment by clementval** [comment]
@MDosky you should not commit the submodule `omni-compiler`

**Comment by MDosky** [comment]
Ah?! Why was it merged?!
I remade the branch and pushed it again on my repo.

**Comment by clementval** [comment]
No but as it conflict with the master, travis cannot run properly

**Comment by MDosky** [comment]
The results will be something like this: `89% tests passed, 36 tests failed out of 322`
I haven't check them all, but it should be the code comparisons.

**Comment by MDosky** [comment]
Ok, I'll open a new one, I'm doing a mess.

**Pull request closed without merging**
