### PR TITLE
Script arg

### PR DESCRIPTION
**Pull request by arporter**
## Status
**REVIEW**

## Description
This PR is for changes to allow the name of a script to be passed to CLAW. I don't envisage using the bash script to drive CLAW when using Python so I haven't modified that script. There is also some preparatory re-factoring ready to support Python-driven transformations. (See https://github.com/stfc/claw-compiler/issues/2)

Please note that I am not a Java programmer so there may well be places where I could do things in a better way - if so then please say!

### CODE REVIEW

**Comment by clementval** [comment]
@arporter I think what you did is fine but we can maybe have only `ClawTranslatorDriver` (as base class directly) and your specilized `ClawPythonTranslatorDriver` will extend it.

**Comment by arporter** [comment]
@clementval OK, I'll change it...

**Comment by arporter** [comment]
@clementval I'm in the process of changing it but am learning that Java always calls the constructor of the parent class. It attempts to do this by automatically adding a call to the parameter-less constructor. Since `ClawTranslatorDriver` does not have one the compilation fails. I've therefore added such a constructor (which is empty) to `ClawTranslatorDriver`.

**Comment by arporter** [comment]
I've done my second attempt in a new branch (since it would otherwise have meant undoing things) so closing this PR.

**Pull request closed without merging**
