### PR TITLE
Changed cx2t coding style

### PR DESCRIPTION
**Pull request by FrostyMike**
## Status

**REVIEW**

### CODE REVIEW

**Review by clementval — COMMENTED** [review]
Do you plan to merge this PR before #600? If so, can we have the change in [README.dev.md](README.dev.md) as part of this PR?

**Comment by FrostyMike** [comment]
> Do you plan to merge this PR before #600? If so, can we have the change in [README.dev.md](README.dev.md) as part of this PR?

Fine

**Review by lxavier — APPROVED** [review]
I assume this is formating only - once the travis test are ok you can merge, thx !

**Comment by FrostyMike** [comment]
> I assume this is formating only - once the travis test are ok you can merge, thx !

Unfortunately travis test will not be ok. This is not due to any changes from this pull request though, it is currently broken on master, because Sonar discontinued the old java version. I fixed it in the main pull request with the new driver.
Is it okif I force-merge it?

**Comment by clementval** [comment]
> > I assume this is formating only - once the travis test are ok you can merge, thx !
> 
> Unfortunately travis test will not be ok. This is not due to any changes from this pull request though, it is currently broken on master, because Sonar discontinued the old java version. I fixed it in the main pull request with the new driver.
> Is it okif I force-merge it?

Fine if the rest of travis has no error. I just had a look at the latest run and there are some errors related to the build. 

```
[javac] /home/travis/build/claw-project/claw-compiler/cx2t/src/claw/wani/report/ClawTransformationReport.java:16: error: cannot find symbol
2610    [javac] import claw.wani.ClawVersion;
2611    [javac]                 ^
2612    [javac]   symbol:   class ClawVersion
2613    [javac]   location: package claw.wani
2614    [javac] /home/travis/build/claw-project/claw-compiler/cx2t/src/claw/wani/report/ClawTransformationReport.java:96: error: cannot find symbol
2615    [javac]         infos.add(new String[] { "CLAW Compiler", ClawVersion.VERSION });
2616    [javac]                                                   ^
2617    [javac]   symbol:   variable ClawVersion
2618    [javac]   location: class ClawTransformationReport
2619    [javac] 2 errors
```

**Comment by clementval** [comment]
@lxavier @FrostyMike You can go ahead with this PR from my side. As a side comment, after review 50% of the PR #604 I'm not a big fan of the new coding style. I find it less clear to read especially with the braces placement for if/else statements and for's. Anyway if you guys are comfortable with that go ahead.

**Pull request merged**
